### ISSUE TITLE
declare real variables with KINDs

### ISSUE THREAD

**Issue by Beliavsky** [rbitr/llm.f90#1]
You wrote about Fortran that it is "harder to find answers to questions". Please consider joining [Fortran Discourse](https://fortran-lang.discourse.group/)

I suggest not using default `real` declarations. You could define

`integer, parameter :: wp = kind(1.0)`

and then declare variables as

`real(kind=wp)`

That way you can change the entire code to double precision by writing

`integer, parameter :: wp = kind(1.0d0)`

This is discussed at https://stevelionel.com/drfortran/2017/03/27/doctor-fortran-in-it-takes-all-kinds/ .

**Comment by rbitr** [comment]
Thank you for the suggestion and the invitation. I made the edit as suggested.
